"""empty message

Revision ID: 079f27e433ed
Revises: 3d80ece7a432
Create Date: 2023-04-13 17:03:15.286326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079f27e433ed'
down_revision = '3d80ece7a432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
