"""empty message

Revision ID: 3307172d5d22
Revises: 079f27e433ed
Create Date: 2023-04-16 10:06:07.112491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3307172d5d22'
down_revision = '079f27e433ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
