"""delete unique message.email

Revision ID: 3d80ece7a432
Revises: 3917f4803244
Create Date: 2023-02-12 13:01:09.727424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d80ece7a432'
down_revision = '3917f4803244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_unique_constraint('message_email_key', ['email'])

    # ### end Alembic commands ###
