"""empty message

Revision ID: 785d78a46248
Revises: 3307172d5d22
Create Date: 2023-04-18 10:21:27.785981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785d78a46248'
down_revision = '3307172d5d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_preview', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_preview')

    # ### end Alembic commands ###
